package com.theironyard.charlotte.entities;

import javax.persistence.*;

@Entity
@Table(name = "users")
public class User {
    // @Id specifies that this column is the ID
    // column for the table. This is the PRIMARY KEY
    // for this table.
    @Id

    // @GeneratedValue means that this will be automatically
    // generated by the database we are using. We do not provide
    // this information to the entity- we get it from the database.
    @GeneratedValue
    int id;

    // non-nullable columns for the rest of the data
    // this means that we have to provide values for these
    // before we can save them.
    @Column(nullable = false)
    String username;

    @Column(nullable = false)
    String address;

    @Column(nullable = false)
    String email;

    // public getters/setters for package-protected fields
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}